version: '3.8'

services:
  # Site Web (PHP/Apache)
  www:
    build: .
    container_name: movehelp_web
    ports:
      - "8080:80"  # Accessible via http://localhost:8080
    volumes:
      - .:/var/www/html # Synchronise  le dossier PC avec le conteneur
    depends_on:
      - db

  #Base de données (MySQL)
  db:
    image: mysql:8.0
    container_name: movehelp_db
    
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bdd_7_5
      MYSQL_USER: grp_7_5
      MYSQL_PASSWORD: T0noTMCBcQKwOP
    volumes:
      - db_data:/var/lib/mysql   # Pour ne pas perdre les données si on éteint

  # phpMyAdmin (Interface BDD)
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: movehelp_pma
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80" # Accessible via http://localhost:8081
    depends_on:
      - db

# Volume pour la persistance des données
volumes:
  db_data: